apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingres-rabbitmq
spec:
  rules:
  - host: rabbitmq.nginx
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rabbitmq
            port:
              number: 15672
  ingressClassName: nginx
